### ISSUE TITLE
postsql sample failed

### ISSUE THREAD

**Issue by yungezz** [Azure-Samples/ansible-playbooks#47] opened 2018-09-20 01:58 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting

```

### Minimal steps to reproduce
>

### Any log messages given by the failure
https://travis-ci.org/Azure-Samples/ansible-playbooks/jobs/430340484
```
TASK [Create PostgreSQL Server] ************************************************
 [WARNING]: Azure API profile latest does not define an entry for
PostgreSQLManagementClient
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the PostgreSQL Server instance: Azure Error: ProvisioningDisabled\nMessage: Gen4 hardware is not supported for this region."}
	to retry, use: --limit @/home/travis/build/Azure-Samples/ansible-playbooks/ansible-playbooks/postgresql_create.retry
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1   
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Fred-sun** [comment] 2018-10-09 05:04
@zikalino

**Comment by Fred-sun** [comment] 2018-10-15 09:17
This error log caused by resource group location (eastus resource group create postsqserver, if  set  region B_Gen5_1 will get this fail) . Westeurope support Gen4 (sku name: GP_Gen4_2) and Gen5 (sku name: B_Gen5_1) , Eastus only support Gen5.  Thanks!

**Comment by Fred-sun** [comment] 2018-10-26 06:15
@yungezz @zikalino

**Comment by Fred-sun** [comment] 2018-11-05 07:48
@zikalino

**Comment by Fred-sun** [comment] 2018-11-21 06:48
@zikalino The region parameters for creating postsqlserver differ depending on the resource group location, Could you help check this issue? Thanks!

**Comment by Fred-sun** [comment] 2018-12-03 09:14
@yungezz @zikalino

**Comment by Fred-sun** [comment] 2018-12-14 03:15
@yungezz @zikalino How about the issue going ahead? a bug need to be fixed or this is not a bug? thanks!

**Comment by Fred-sun** [comment] 2018-12-25 06:04
@yungezz @zikalino

**Comment by Fred-sun** [comment] 2019-01-08 04:02
@yungezz @zikalino

**Comment by Fred-sun** [comment] 2019-01-21 06:42
@zikalino This error log may caused by resource group location. Westeurope support Gen4 (sku name: GP_Gen4_2) and Gen5 (sku name: B_Gen5_1) , Eastus only support Gen5. Please help take a look and verify this is a issue or not?  Thanks!

**Comment by zikalino** [comment] 2019-01-21 06:44
@Fred-sun could you replace Gen4 with Gen5 in this sample and create PR?

**Comment by Fred-sun** [comment] 2019-01-21 07:51
@zikalino Please review[ #60](https://github.com/Azure-Samples/ansible-playbooks/pull/60) ,Thanks!

**Comment by zikalino** [comment] 2019-01-21 08:13
Fixed now by Fred

**Closed by zikalino** 2019-01-21 08:13 UTC
